### ISSUE TITLE
Exact command for obtaining 3D Pose?

### ISSUE THREAD

**Issue by ShaminiKoravuna** [miu200521358/3d-pose-baseline-vmd#12]
Hello everyone,

I'm trying to run the following command for getting 3D output

`python src/openpose_3dpose_sandbox_vmd.py --camera_frame --residual --batch_norm --dropout 0.5 --max_norm --evaluateActionWise --epochs 200 --load 4874200 --openpose output/
`
But I'am getting the following error

```
INFO:openpose_utils:start reading data: openpose_output_output//json
Traceback (most recent call last):
 File "src/openpose_3dpose_sandbox_vmd.py", line 481, in <module>
   tf.app.run()
 File "C:\Program Files\Anaconda3\envs\pose3Drnn\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
   _sys.exit(main(argv))
 File "src/openpose_3dpose_sandbox_vmd.py", line 78, in main
   start_frame_index, smoothed = openpose_utils.read_openpose_json("{0}/json".format(openpose_output_dir), idx, FLAGS.verbose == 3)
 File "C:\3d-pose-baseline-vmd\src\openpose_utils.py", line 28, in read_openpose_json
   json_files = os.listdir(openpose_output_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'openpose_output_output//json'
```
Can anyone suggest me the proper command for getting the 3D output?

Thanks in advance

**Comment by jxx840757943** [comment]
I face the same error as you faced.
Have already solve it?
If solved, could you please share how to?
Thanks
