### ISSUE TITLE
Json files generated using OpenPose v1.5.0 cannot be parsed correctly 

### ISSUE THREAD

**Issue by CrazyReason** [miu200521358/3d-pose-baseline-vmd#15]
1. Your operating system
win10_64
2. Your tensorflow version
tensorflow (1.13.1)
3. Your python version
Python 3.6.2
4. The stack trace of the error that you see

`Please output detailed logs or enter yes or no.
If nothing is entered and ENTER is pressed, normal animation GIF of log and motion is output.
For detailed logs, debug images for each frame are additionally output. (It will take time for that)
If warn is specified, animation GIF is not output. (That is earlier)
** Detailed log[yes/no/warn]: yes
h:\ProgramData\Anaconda3\envs\openmmd\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
DEBUG:__main__:FLAGS.person_idx=1
INFO:openpose_utils:start reading data: F:\tf_python\openmmd_v1\openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended\user_video/json
DEBUG:openpose_utils:reading bubbletop_000000000000_keypoints.json
DEBUG:openpose_utils:found [774.401, 125.849, 789.965, 180.752, 746.972, 182.72, 743.03, 259.106, 733.191, 317.88, 827.293, 180.72, 838.992, 259.109, 792.009, 272.851, 780.254, 319.82, 756.74, 319.814, 746.953, 406.027, 744.958, 478.521, 807.639, 319.835, 799.788, 409.96, 793.953, 472.644, 772.334, 116.177, 782.22, 116.159, 0, 0, 799.85, 119.978, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 746.933, 478.529] for frame 0
DEBUG:openpose_utils:reading bubbletop_000000000001_keypoints.json
Traceback (most recent call last):
  File "src/openpose_3dpose_sandbox_vmd.py", line 481, in <module>
    tf.app.run()
  File "h:\ProgramData\Anaconda3\envs\openmmd\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "src/openpose_3dpose_sandbox_vmd.py", line 78, in main
    start_frame_index, smoothed = openpose_utils.read_openpose_json("{0}/json".format(openpose_output_dir), idx, FLAGS.verbose == 3)
  File "F:\tf_python\openmmd_v1\3d-pose-baseline-vmd-20190505\src\openpose_utils.py", line 92, in read_openpose_json
    _tmp_points[n][_data_idx] = _tmp_data[o]
IndexError: list index out of range`

The newly generated json file array is as follows, a total of 75 data, parsing error：
{"version":1.3,"people":[{"person_id":[-1],"pose_keypoints_2d":[774.401,125.849,0.334804,789.965,180.752,0.597887,746.972,182.72,0.567739,743.03,259.106,0.32019,733.191,317.88,0.221334,827.293,180.72,0.576237,838.992,259.109,0.477992,792.009,272.851,0.128871,780.254,319.82,0.382107,756.74,319.814,0.369866,746.953,406.027,0.26066,744.958,478.521,0.0741534,807.639,319.835,0.397492,799.788,409.96,0.262418,793.953,472.644,0.0589618,772.334,116.177,0.215872,782.22,116.159,0.29794,0,0,0,799.85,119.978,0.240411,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,746.933,478.529,0.0732574],"face_keypoints_2d":[],"hand_left_keypoints_2d":[],"hand_right_keypoints_2d":[],"pose_keypoints_3d":[],"face_keypoints_3d":[],"hand_left_keypoints_3d":[],"hand_right_keypoints_3d":[]}]}

The original generated json file array is as follows, a total of 54 data, can be correctly parsed：
{"version":1.2,"people":[{"pose_keypoints_2d":[951.37,341.375,0.925202,957.166,424.362,0.913087,902.76,424.408,0.94408,879.865,518.987,0.887315,885.573,610.552,0.882004,1017.34,424.263,0.921865,1037.34,519.015,0.872157,1031.61,607.874,0.858192,925.526,607.682,0.787106,931.312,742.361,0.898836,931.394,879.665,0.884451,997.168,607.608,0.837472,997.19,742.374,0.90173,997.237,876.917,0.88855,937.089,332.648,0.920358,968.491,329.949,0.932332,925.634,344.219,0.740899,985.805,338.522,0.837696],"face_keypoints_2d":[],"hand_left_keypoints_2d":[],"hand_right_keypoints_2d":[],"pose_keypoints_3d":[],"face_keypoints_3d":[],"hand_left_keypoints_3d":[],"hand_right_keypoints_3d":[]}]}

The first time you use it, don't know which bone each key point corresponds to. If you can fix this error, thank you very much.

**Comment by CrazyReason** [comment]
Append to OpenPoseDemo.exe --model_pose COCO
