### ISSUE TITLE
Output is wrong on the legs when using with Openpose 1.5.1

### ISSUE THREAD

**Issue by xamxixixo** [miu200521358/3d-pose-baseline-vmd#17]
Hello,

Since my GPU is RTX 2080ti, and openpose 1.3 could not run with the GPU, I had to replace  openpose to 1.5.1 version. Everything still works, but only the legs are at the wrong positions, and seem to be not moving.

At first it didn't work with Openpose 1.5.1. To make it work I have done:

- Download pose_iter_584000.caffemodel from the getmodels.bat for the body_25 model. The file isn't required in the Openpose 1.3, which is used in your program.
- Changed the code of `/src/openpose_3dpose_sandbox_vmd.py`, line 104, to `for o in range(0,len(_tmp_data),5):`, from 3 to 5. Because when it was 3 your program errored (when executed the "3D Pose Baseline to VMD"/OpenposeTo3D.bat):

```
(tensorflow) C:\Users\abc\Desktop\OpenMMD_openpose1.5.1_recommended\3D Pose Baseline to VMD>OpenposeTo3D.bat

(tensorflow) C:\Users\abc\Desktop\OpenMMD_openpose1.5.1_recommended\3D Pose Baseline to VMD>∩╗┐es (40 sloc) 1.62 KB
'∩╗┐es' is not recognized as an internal or external command,
operable program or batch file.
Please input the path of result from OpenPose Execution: JSON folder
Input is limited to English characters and numbers.
Γûáthe path of result from OpenPose Execution (JSON folder): ../_json
--------------
The max number of people in your video.
If no input and press Enter, the number of be set to default: 1 person.
The max number of people in your video: 1
--------------
If you want the detailed information of GIF, input yes.
If no input and press Enter, the generation setting of GIF will be set to default.
warn If you input warn, then no GIF will be generated.
the detailed information[yes/no/warn]:
experiments\All\dropout_0.5\epochs_200\lr_0.001\residual\depth_2\ls1024\bs64\np\maxnorm\batch_normalization\use_stacked_hourglass\predict_17
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file experiments\All\dropout_0.5\epochs_200\lr_0.001\residual\depth_2\ls1024\bs64\np\maxnorm\batch_normalization\use_stacked_hourglass\predict_17\log already exists.
Error occurred while processing: experiments\All\dropout_0.5\epochs_200\lr_0.001\residual\depth_2\ls1024\bs64\np\maxnorm\batch_normalization\use_stacked_hourglass\predict_17\log.
WARNING:tensorflow:From src/openpose_3dpose_sandbox_vmd.py:484: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From src/openpose_3dpose_sandbox_vmd.py:484: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

I0108 23:03:22.422491 12412 openpose_3dpose_sandbox_vmd.py:52] start reading data
Traceback (most recent call last):
  File "src/openpose_3dpose_sandbox_vmd.py", line 484, in <module>
    tf.app.run()
  File "C:\Users\abc\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\abc\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\abc\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "src/openpose_3dpose_sandbox_vmd.py", line 283, in main
    smoothed = read_openpose_json(now_str, idx, subdir)
  File "src/openpose_3dpose_sandbox_vmd.py", line 110, in read_openpose_json
    _tmp_points[n][_data_idx] = _tmp_data[o]
IndexError: list index out of range
```

So, by changing the range to 5, I managed to run the program. But only that the knees were held at higher positions, and the legs weren't moving. Please take at look at the gif file that was generated by Openposeto3D.bat:
![72083674-10c56f80-32b7-11ea-8821-29ad73dd6da6](https://user-images.githubusercontent.com/37895275/73186840-48b11d00-40d5-11ea-80bc-b9322c44802e.gif)
I am stuck here now. How to fix it?
Thank you.

**Comment by fantastic-beasts** [comment]
I did the same as you did to replace openpose1.3.1 with 1.5.1, and I will be at this step because of this problem. We are confused together

**Comment by fantastic-beasts** [comment]
I did the same as you did to replace openpose1.3.1 with 1.5.1, and I will stop at this step because of this problem. We are confused together
